/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables;


import com.mick.mchat.jooq.UUIDConverter;
import com.mick.mchat.jooq.model.Indexes;
import com.mick.mchat.jooq.model.Keys;
import com.mick.mchat.jooq.model.Mchat;
import com.mick.mchat.jooq.model.enums.ConversationStatus;
import com.mick.mchat.jooq.model.enums.ConversationType;
import com.mick.mchat.jooq.model.tables.records.ConversationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conversation extends TableImpl<ConversationRecord> {

    private static final long serialVersionUID = -1839154216;

    /**
     * The reference instance of <code>mchat.conversation</code>
     */
    public static final Conversation CONVERSATION = new Conversation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConversationRecord> getRecordType() {
        return ConversationRecord.class;
    }

    /**
     * The column <code>mchat.conversation.uuid</code>.
     */
    public final TableField<ConversationRecord, UUID> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY(16).nullable(false), this, "", new UUIDConverter());

    /**
     * The column <code>mchat.conversation.name</code>.
     */
    public final TableField<ConversationRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>mchat.conversation.status</code>.
     */
    public final TableField<ConversationRecord, ConversationStatus> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(8).nullable(false).defaultValue(org.jooq.impl.DSL.inline("ACTIVE", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(com.mick.mchat.jooq.model.enums.ConversationStatus.class), this, "");

    /**
     * The column <code>mchat.conversation.type</code>.
     */
    public final TableField<ConversationRecord, ConversationType> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(7).nullable(false).defaultValue(org.jooq.impl.DSL.inline("PRIVATE", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(com.mick.mchat.jooq.model.enums.ConversationType.class), this, "");

    /**
     * The column <code>mchat.conversation.date_created</code>.
     */
    public final TableField<ConversationRecord, Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP(6)", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>mchat.conversation</code> table reference
     */
    public Conversation() {
        this(DSL.name("conversation"), null);
    }

    /**
     * Create an aliased <code>mchat.conversation</code> table reference
     */
    public Conversation(String alias) {
        this(DSL.name(alias), CONVERSATION);
    }

    /**
     * Create an aliased <code>mchat.conversation</code> table reference
     */
    public Conversation(Name alias) {
        this(alias, CONVERSATION);
    }

    private Conversation(Name alias, Table<ConversationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Conversation(Name alias, Table<ConversationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Conversation(Table<O> child, ForeignKey<O, ConversationRecord> key) {
        super(child, key, CONVERSATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mchat.MCHAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONVERSATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConversationRecord> getPrimaryKey() {
        return Keys.KEY_CONVERSATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConversationRecord>> getKeys() {
        return Arrays.<UniqueKey<ConversationRecord>>asList(Keys.KEY_CONVERSATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conversation as(String alias) {
        return new Conversation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conversation as(Name alias) {
        return new Conversation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Conversation rename(String name) {
        return new Conversation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Conversation rename(Name name) {
        return new Conversation(name, null);
    }
}
