/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.records;


import com.mick.mchat.jooq.model.enums.MessageType;
import com.mick.mchat.jooq.model.tables.Message;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record6<UUID, UUID, UUID, MessageType, String, Timestamp> {

    private static final long serialVersionUID = -1724087280;

    /**
     * Setter for <code>mchat.message.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>mchat.message.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>mchat.message.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>mchat.message.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>mchat.message.conversation_uuid</code>.
     */
    public void setConversationUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>mchat.message.conversation_uuid</code>.
     */
    public UUID getConversationUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>mchat.message.type</code>.
     */
    public void setType(MessageType value) {
        set(3, value);
    }

    /**
     * Getter for <code>mchat.message.type</code>.
     */
    public MessageType getType() {
        return (MessageType) get(3);
    }

    /**
     * Setter for <code>mchat.message.body</code>.
     */
    public void setBody(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mchat.message.body</code>.
     */
    public String getBody() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mchat.message.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mchat.message.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UUID, UUID, UUID, MessageType, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UUID, UUID, UUID, MessageType, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Message.MESSAGE.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Message.MESSAGE.USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field3() {
        return Message.MESSAGE.CONVERSATION_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MessageType> field4() {
        return Message.MESSAGE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Message.MESSAGE.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Message.MESSAGE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component3() {
        return getConversationUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageType component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value3() {
        return getConversationUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageType value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value2(UUID value) {
        setUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value3(UUID value) {
        setConversationUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value4(MessageType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value5(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value6(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord values(UUID value1, UUID value2, UUID value3, MessageType value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(UUID uuid, UUID userUuid, UUID conversationUuid, MessageType type, String body, Timestamp dateCreated) {
        super(Message.MESSAGE);

        set(0, uuid);
        set(1, userUuid);
        set(2, conversationUuid);
        set(3, type);
        set(4, body);
        set(5, dateCreated);
    }
}
