CREATE DATABASE IF NOT EXISTS mchat DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
USE mchat;


CREATE TABLE IF NOT EXISTS user (
  uuid BINARY(16) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255),
  date_created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY(uuid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS conversation (
  uuid BINARY(16) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  type ENUM('GROUP','PRIVATE') NOT NULL DEFAULT 'PRIVATE',
  date_created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY(uuid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_conversation (
  uuid BINARY(16) NOT NULL,
  conversation_uuid BINARY(16) NOT NULL,
  user_uuid BINARY(16) NOT NULL,
  date_created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY(uuid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS message (
  uuid BINARY(16) NOT NULL,
  user_uuid BINARY(16) NOT NULL,
  conversation_uuid BINARY(16) NOT NULL,
  type enum('TEXT', 'IMAGE') NOT NULL DEFAULT 'TEXT',
  body TEXT CHARACTER SET latin1 COLLATE latin1_general_cs,
  date_created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY(uuid)
) ENGINE=InnoDB;
