export const CONVERSATIONS_GET_ALL_RESPONSE = 'CONVERSATIONS_GET_ALL_RESPONSE';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const CHAT_MESSAGE = 'CHAT_MESSAGE';
export const CURRENT_USER = 'CURRENT_USER';
export const ERROR = 'ERROR';