/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.pojos;


import com.mick.mchat.jooq.model.enums.ConversationStatus;
import com.mick.mchat.jooq.model.enums.ConversationType;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conversation implements Serializable {

    private static final long serialVersionUID = -981735897;

    private UUID               uuid;
    private String             name;
    private ConversationStatus status;
    private ConversationType   type;
    private Timestamp          dateCreated;

    public Conversation() {}

    public Conversation(Conversation value) {
        this.uuid = value.uuid;
        this.name = value.name;
        this.status = value.status;
        this.type = value.type;
        this.dateCreated = value.dateCreated;
    }

    public Conversation(
        UUID               uuid,
        String             name,
        ConversationStatus status,
        ConversationType   type,
        Timestamp          dateCreated
    ) {
        this.uuid = uuid;
        this.name = name;
        this.status = status;
        this.type = type;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ConversationStatus getStatus() {
        return this.status;
    }

    public void setStatus(ConversationStatus status) {
        this.status = status;
    }

    public ConversationType getType() {
        return this.type;
    }

    public void setType(ConversationType type) {
        this.type = type;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Conversation (");

        sb.append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(status);
        sb.append(", ").append(type);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
