/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.pojos;


import com.mick.mchat.jooq.model.enums.MessageType;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 2003037015;

    private UUID        uuid;
    private UUID        userUuid;
    private UUID        conversationUuid;
    private MessageType type;
    private String      body;
    private Timestamp   dateCreated;

    public Message() {}

    public Message(Message value) {
        this.uuid = value.uuid;
        this.userUuid = value.userUuid;
        this.conversationUuid = value.conversationUuid;
        this.type = value.type;
        this.body = value.body;
        this.dateCreated = value.dateCreated;
    }

    public Message(
        UUID        uuid,
        UUID        userUuid,
        UUID        conversationUuid,
        MessageType type,
        String      body,
        Timestamp   dateCreated
    ) {
        this.uuid = uuid;
        this.userUuid = userUuid;
        this.conversationUuid = conversationUuid;
        this.type = type;
        this.body = body;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public UUID getUserUuid() {
        return this.userUuid;
    }

    public void setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
    }

    public UUID getConversationUuid() {
        return this.conversationUuid;
    }

    public void setConversationUuid(UUID conversationUuid) {
        this.conversationUuid = conversationUuid;
    }

    public MessageType getType() {
        return this.type;
    }

    public void setType(MessageType type) {
        this.type = type;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(uuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(conversationUuid);
        sb.append(", ").append(type);
        sb.append(", ").append(body);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
