/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConversation implements Serializable {

    private static final long serialVersionUID = 838748860;

    private UUID      uuid;
    private UUID      conversationUuid;
    private UUID      userUuid;
    private Timestamp dateCreated;

    public UserConversation() {}

    public UserConversation(UserConversation value) {
        this.uuid = value.uuid;
        this.conversationUuid = value.conversationUuid;
        this.userUuid = value.userUuid;
        this.dateCreated = value.dateCreated;
    }

    public UserConversation(
        UUID      uuid,
        UUID      conversationUuid,
        UUID      userUuid,
        Timestamp dateCreated
    ) {
        this.uuid = uuid;
        this.conversationUuid = conversationUuid;
        this.userUuid = userUuid;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public UUID getConversationUuid() {
        return this.conversationUuid;
    }

    public void setConversationUuid(UUID conversationUuid) {
        this.conversationUuid = conversationUuid;
    }

    public UUID getUserUuid() {
        return this.userUuid;
    }

    public void setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserConversation (");

        sb.append(uuid);
        sb.append(", ").append(conversationUuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
