/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1820520649;

    private UUID      uuid;
    private String    username;
    private String    password;
    private String    avatarUrl;
    private Timestamp dateCreated;

    public User() {}

    public User(User value) {
        this.uuid = value.uuid;
        this.username = value.username;
        this.password = value.password;
        this.avatarUrl = value.avatarUrl;
        this.dateCreated = value.dateCreated;
    }

    public User(
        UUID      uuid,
        String    username,
        String    password,
        String    avatarUrl,
        Timestamp dateCreated
    ) {
        this.uuid = uuid;
        this.username = username;
        this.password = password;
        this.avatarUrl = avatarUrl;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(uuid);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
