/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.daos;


import com.mick.mchat.jooq.model.enums.ConversationStatus;
import com.mick.mchat.jooq.model.enums.ConversationType;
import com.mick.mchat.jooq.model.tables.Conversation;
import com.mick.mchat.jooq.model.tables.records.ConversationRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConversationDao extends DAOImpl<ConversationRecord, com.mick.mchat.jooq.model.tables.pojos.Conversation, UUID> {

    /**
     * Create a new ConversationDao without any configuration
     */
    public ConversationDao() {
        super(Conversation.CONVERSATION, com.mick.mchat.jooq.model.tables.pojos.Conversation.class);
    }

    /**
     * Create a new ConversationDao with an attached configuration
     */
    public ConversationDao(Configuration configuration) {
        super(Conversation.CONVERSATION, com.mick.mchat.jooq.model.tables.pojos.Conversation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.mick.mchat.jooq.model.tables.pojos.Conversation object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Conversation> fetchByUuid(UUID... values) {
        return fetch(Conversation.CONVERSATION.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public com.mick.mchat.jooq.model.tables.pojos.Conversation fetchOneByUuid(UUID value) {
        return fetchOne(Conversation.CONVERSATION.UUID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Conversation> fetchByName(String... values) {
        return fetch(Conversation.CONVERSATION.NAME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Conversation> fetchByStatus(ConversationStatus... values) {
        return fetch(Conversation.CONVERSATION.STATUS, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Conversation> fetchByType(ConversationType... values) {
        return fetch(Conversation.CONVERSATION.TYPE, values);
    }

    /**
     * Fetch records that have <code>date_created IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Conversation> fetchByDateCreated(Timestamp... values) {
        return fetch(Conversation.CONVERSATION.DATE_CREATED, values);
    }
}
