/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.daos;


import com.mick.mchat.jooq.model.enums.MessageType;
import com.mick.mchat.jooq.model.tables.Message;
import com.mick.mchat.jooq.model.tables.records.MessageRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageDao extends DAOImpl<MessageRecord, com.mick.mchat.jooq.model.tables.pojos.Message, UUID> {

    /**
     * Create a new MessageDao without any configuration
     */
    public MessageDao() {
        super(Message.MESSAGE, com.mick.mchat.jooq.model.tables.pojos.Message.class);
    }

    /**
     * Create a new MessageDao with an attached configuration
     */
    public MessageDao(Configuration configuration) {
        super(Message.MESSAGE, com.mick.mchat.jooq.model.tables.pojos.Message.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.mick.mchat.jooq.model.tables.pojos.Message object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByUuid(UUID... values) {
        return fetch(Message.MESSAGE.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public com.mick.mchat.jooq.model.tables.pojos.Message fetchOneByUuid(UUID value) {
        return fetchOne(Message.MESSAGE.UUID, value);
    }

    /**
     * Fetch records that have <code>user_uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByUserUuid(UUID... values) {
        return fetch(Message.MESSAGE.USER_UUID, values);
    }

    /**
     * Fetch records that have <code>conversation_uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByConversationUuid(UUID... values) {
        return fetch(Message.MESSAGE.CONVERSATION_UUID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByType(MessageType... values) {
        return fetch(Message.MESSAGE.TYPE, values);
    }

    /**
     * Fetch records that have <code>body IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByBody(String... values) {
        return fetch(Message.MESSAGE.BODY, values);
    }

    /**
     * Fetch records that have <code>date_created IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.Message> fetchByDateCreated(Timestamp... values) {
        return fetch(Message.MESSAGE.DATE_CREATED, values);
    }
}
