/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model.tables.daos;


import com.mick.mchat.jooq.model.tables.UserConversation;
import com.mick.mchat.jooq.model.tables.records.UserConversationRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConversationDao extends DAOImpl<UserConversationRecord, com.mick.mchat.jooq.model.tables.pojos.UserConversation, UUID> {

    /**
     * Create a new UserConversationDao without any configuration
     */
    public UserConversationDao() {
        super(UserConversation.USER_CONVERSATION, com.mick.mchat.jooq.model.tables.pojos.UserConversation.class);
    }

    /**
     * Create a new UserConversationDao with an attached configuration
     */
    public UserConversationDao(Configuration configuration) {
        super(UserConversation.USER_CONVERSATION, com.mick.mchat.jooq.model.tables.pojos.UserConversation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.mick.mchat.jooq.model.tables.pojos.UserConversation object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.UserConversation> fetchByUuid(UUID... values) {
        return fetch(UserConversation.USER_CONVERSATION.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public com.mick.mchat.jooq.model.tables.pojos.UserConversation fetchOneByUuid(UUID value) {
        return fetchOne(UserConversation.USER_CONVERSATION.UUID, value);
    }

    /**
     * Fetch records that have <code>conversation_uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.UserConversation> fetchByConversationUuid(UUID... values) {
        return fetch(UserConversation.USER_CONVERSATION.CONVERSATION_UUID, values);
    }

    /**
     * Fetch records that have <code>user_uuid IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.UserConversation> fetchByUserUuid(UUID... values) {
        return fetch(UserConversation.USER_CONVERSATION.USER_UUID, values);
    }

    /**
     * Fetch records that have <code>date_created IN (values)</code>
     */
    public List<com.mick.mchat.jooq.model.tables.pojos.UserConversation> fetchByDateCreated(Timestamp... values) {
        return fetch(UserConversation.USER_CONVERSATION.DATE_CREATED, values);
    }
}
