/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model;


import com.mick.mchat.jooq.model.tables.Conversation;
import com.mick.mchat.jooq.model.tables.Message;
import com.mick.mchat.jooq.model.tables.User;
import com.mick.mchat.jooq.model.tables.UserConversation;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>mchat</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONVERSATION_PRIMARY = Indexes0.CONVERSATION_PRIMARY;
    public static final Index MESSAGE_PRIMARY = Indexes0.MESSAGE_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_CONVERSATION_PRIMARY = Indexes0.USER_CONVERSATION_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONVERSATION_PRIMARY = Internal.createIndex("PRIMARY", Conversation.CONVERSATION, new OrderField[] { Conversation.CONVERSATION.UUID }, true);
        public static Index MESSAGE_PRIMARY = Internal.createIndex("PRIMARY", Message.MESSAGE, new OrderField[] { Message.MESSAGE.UUID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.UUID }, true);
        public static Index USER_CONVERSATION_PRIMARY = Internal.createIndex("PRIMARY", UserConversation.USER_CONVERSATION, new OrderField[] { UserConversation.USER_CONVERSATION.UUID }, true);
    }
}
