/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model;


import com.mick.mchat.jooq.model.tables.Conversation;
import com.mick.mchat.jooq.model.tables.Message;
import com.mick.mchat.jooq.model.tables.User;
import com.mick.mchat.jooq.model.tables.UserConversation;
import com.mick.mchat.jooq.model.tables.records.ConversationRecord;
import com.mick.mchat.jooq.model.tables.records.MessageRecord;
import com.mick.mchat.jooq.model.tables.records.UserConversationRecord;
import com.mick.mchat.jooq.model.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>mchat</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConversationRecord> KEY_CONVERSATION_PRIMARY = UniqueKeys0.KEY_CONVERSATION_PRIMARY;
    public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = UniqueKeys0.KEY_MESSAGE_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserConversationRecord> KEY_USER_CONVERSATION_PRIMARY = UniqueKeys0.KEY_USER_CONVERSATION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ConversationRecord> KEY_CONVERSATION_PRIMARY = Internal.createUniqueKey(Conversation.CONVERSATION, "KEY_conversation_PRIMARY", Conversation.CONVERSATION.UUID);
        public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = Internal.createUniqueKey(Message.MESSAGE, "KEY_message_PRIMARY", Message.MESSAGE.UUID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.UUID);
        public static final UniqueKey<UserConversationRecord> KEY_USER_CONVERSATION_PRIMARY = Internal.createUniqueKey(UserConversation.USER_CONVERSATION, "KEY_user_conversation_PRIMARY", UserConversation.USER_CONVERSATION.UUID);
    }
}
