/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model;


import com.mick.mchat.jooq.model.tables.Conversation;
import com.mick.mchat.jooq.model.tables.Message;
import com.mick.mchat.jooq.model.tables.User;
import com.mick.mchat.jooq.model.tables.UserConversation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mchat extends SchemaImpl {

    private static final long serialVersionUID = -1822913097;

    /**
     * The reference instance of <code>mchat</code>
     */
    public static final Mchat MCHAT = new Mchat();

    /**
     * The table <code>mchat.conversation</code>.
     */
    public final Conversation CONVERSATION = com.mick.mchat.jooq.model.tables.Conversation.CONVERSATION;

    /**
     * The table <code>mchat.message</code>.
     */
    public final Message MESSAGE = com.mick.mchat.jooq.model.tables.Message.MESSAGE;

    /**
     * The table <code>mchat.user</code>.
     */
    public final User USER = com.mick.mchat.jooq.model.tables.User.USER;

    /**
     * The table <code>mchat.user_conversation</code>.
     */
    public final UserConversation USER_CONVERSATION = com.mick.mchat.jooq.model.tables.UserConversation.USER_CONVERSATION;

    /**
     * No further instances allowed
     */
    private Mchat() {
        super("mchat", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Conversation.CONVERSATION,
            Message.MESSAGE,
            User.USER,
            UserConversation.USER_CONVERSATION);
    }
}
