/*
 * This file is generated by jOOQ.
 */
package com.mick.mchat.jooq.model;


import com.mick.mchat.jooq.model.tables.Conversation;
import com.mick.mchat.jooq.model.tables.Message;
import com.mick.mchat.jooq.model.tables.User;
import com.mick.mchat.jooq.model.tables.UserConversation;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mchat
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mchat.conversation</code>.
     */
    public static final Conversation CONVERSATION = com.mick.mchat.jooq.model.tables.Conversation.CONVERSATION;

    /**
     * The table <code>mchat.message</code>.
     */
    public static final Message MESSAGE = com.mick.mchat.jooq.model.tables.Message.MESSAGE;

    /**
     * The table <code>mchat.user</code>.
     */
    public static final User USER = com.mick.mchat.jooq.model.tables.User.USER;

    /**
     * The table <code>mchat.user_conversation</code>.
     */
    public static final UserConversation USER_CONVERSATION = com.mick.mchat.jooq.model.tables.UserConversation.USER_CONVERSATION;
}
